### ISSUE TITLE
Minor features/bug fixes

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [jeanpaulrsoucy/archivist#1]
A collection of minor features and bug fixes, mainly transferred from [Covid19CanadaArchive](https://github.com/ccodwg/Covid19CanadaArchive/).

## download functions (dl_file, html_page, ss_page)

- [x] Parameters could be converted into a single 'args' parameter
- [x] Add 'debug' parameter
- [x] ~~Add more robust timeouts (see [issue](https://github.com/ccodwg/Covid19CanadaArchive/issues/215))~~ (moved to #7)
- [x] ~~When spoofing user agent, randomly pick from a set of modern user agent strings~~ (moved to #4)
- [x] ~~Add useragent support to `html_page` and `ss_page`~~ (moved to #4)

## html_page

- [x] ~~When saving pages with d3 elements, ensure that the d3 elements are saved~~ (moved to #8)
  - https://stackoverflow.com/questions/28671388/getting-an-d3-elements-property-that-is-in-dom-not-in-the-html-with-seleniu
  - https://stackoverflow.com/questions/25356440/need-to-dump-entire-dom-tree-with-element-id-from-selenium-server

## Re-running UUIDs

- [x] When using --uuid, should run in the order provided
- [x] Add automated retries for failed datasets ([example code](https://github.com/ccodwg/Covid19CanadaArchive/issues/187))
- [x] ~~Add ability to re-run a _range_ of datasets~~ (moved to #26)
- [x] Add ability to exclude certain datasets from the run (e.g., --uuid-exclude)
- [x] Add option to run datasets in a random order to reduce load on servers (e.g., --random-order)
- [x] Print re-run code to standard error
- [x] Report failed datasets at bottom of script, for convenience

## Miscellaneous

- [x] Add option to wait between queries
- [x] ~~Add ability to pass environmental variables through a file~~ (moved to #14)
  - [env file using python-dotenv](https://stackoverflow.com/questions/40216311/reading-in-environment-variables-from-an-environment-file)
- [x] ~~Script to grab all embedded datasets and tables and save as a single JSON file~~ (moved to #8)
  - Example use case: NWT dashboard or Alberta info page
